export { default as background } from './background.png';
export { default as round } from './round.png';
export { default as star } from './star.png';
export { default as buttons } from './buttons.png';
export { default as blocks } from './blocks.png';
export { default as starFill } from './starFill.png';
export { default as hands } from './hands.png';
export { default as flares } from './flares.png';
export { default as flaresJSON } from './flares.json';
